# To compare the three window sizes (1 kb, 10 kb, 100 kb) with corresponding step sizes (0.5 kb, 5 kb, 50 kb) 

To compare the three window-size settings, the total number of windows and the mean number of SNPs per window were calculated. For each farm population pair, the interquartile range (IQR) of FST values across all genomic windows was first calculated, and then the median of these pair-specific IQRs was used to summarise FST variability for each window size.

In [1]:
import pandas as pd
import os

In [ ]:
#### run 3 different fst outputs for 3 windowsize respectively

## input
input_1 = "../../../../../analysis/variant_explore/illumina_HC_wgs_XJ4126/06-FST_removed_s16_s17/06-03_poola_fst_by_chr/fst_1000_window_500_step/preprocessed_all_samples_rm_s16_s17_1000_window_500_step.by_chr.fst"
input_10 ="../../../../../analysis/variant_explore/illumina_HC_wgs_XJ4126/06-FST_removed_s16_s17/06-03_poola_fst_by_chr/fst_10000_window_5000_step/preprocessed_all_samples_rm_s16_s17_10000_window_5000_step.by_chr.fst"
input_100 ="../../../../../analysis/variant_explore/illumina_HC_wgs_XJ4126/06-FST_removed_s16_s17/06-03_poola_fst_by_chr/fst_100000_window_50000_step/preprocessed_all_samples_rm_s16_s17_100000_window_50000_step.by_chr.fst"

## when window 1kb, step 0.5kb

In [5]:
data_1 = pd.read_csv(input_1, sep="\t")
data_1

,CHR,POS,SNPs,Fraction_window,Aver_min_coverage,s1_VS_s2,s1_VS_s3,s1_VS_s4,s1_VS_s5,s1_VS_s6,...,s11_VS_s12,s11_VS_s13,s11_VS_s14,s11_VS_s15,s12_VS_s13,s12_VS_s14,s12_VS_s15,s13_VS_s14,s13_VS_s15,s14_VS_s15
0,chr1,3500,1,0.002,15.0,0.010499,0.027574,0.010526,0.010526,0.023158,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,chr1,4000,2,0.009,18.7,0.044609,0.017289,0.007370,0.041955,0.053813,...,0.022707,0.162397,0.070946,0.019931,0.072833,0.022554,0.075697,0.034162,0.261968,0.145159
2,chr1,4500,17,0.084,16.7,0.026257,0.072450,0.036193,0.032917,0.028895,...,0.033710,0.066429,0.048715,0.045837,0.041016,0.021123,0.094945,0.036947,0.101836,0.096880
3,chr1,5000,23,0.110,16.3,0.013336,0.117750,0.037705,0.021230,0.016472,...,0.031176,0.029087,0.045802,0.203764,0.020986,0.020375,0.240722,0.033984,0.202224,0.267287
4,chr1,5500,14,0.138,16.0,0.013212,0.128218,0.034442,0.023357,0.018864,...,0.056320,0.031012,0.089139,0.272391,0.013468,0.012860,0.250458,0.028188,0.238363,0.292563
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479208,chrX,46008000,13,0.990,23.7,0.016327,0.033433,0.132699,0.047511,0.013350,...,0.046399,0.090547,0.026606,0.108377,0.212475,0.110275,0.068177,0.031879,0.273707,0.165922
479209,chrX,46008500,10,0.858,22.7,0.010030,0.025312,0.140341,0.023623,0.011931,...,0.080927,0.099017,0.030817,0.130130,0.258960,0.120398,0.064684,0.060303,0.305733,0.157031
479210,chrX,46009000,30,0.776,19.3,0.009913,0.018623,0.043247,0.037167,0.011659,...,0.052425,0.045391,0.030192,0.084520,0.110255,0.040202,0.029864,0.043709,0.150260,0.061879
479211,chrX,46009500,71,0.779,18.9,0.016738,0.015756,0.031255,0.046001,0.018246,...,0.035142,0.043591,0.034565,0.095281,0.071892,0.048819,0.087324,0.018987,0.120480,0.101873
479212,chrX,46010000,43,0.370,19.9,0.020514,0.019361,0.026889,0.049603,0.021955,...,0.031227,0.061325,0.038849,0.138032,0.091706,0.060181,0.120840,0.021519,0.177332,0.144256

In [7]:
## check the first few rows of the data for chromosome 2...
data_1[data_1["CHR"] == "chr2"].head()

,CHR,POS,SNPs,Fraction_window,Aver_min_coverage,s1_VS_s2,s1_VS_s3,s1_VS_s4,s1_VS_s5,s1_VS_s6,...,s11_VS_s12,s11_VS_s13,s11_VS_s14,s11_VS_s15,s12_VS_s13,s12_VS_s14,s12_VS_s15,s13_VS_s14,s13_VS_s15,s14_VS_s15
75350,chr2,500,1,0.012,15.1,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.082313,0.000000,0.000000,0.060288,0.000000,0.039958,0.000000,0.065628
75351,chr2,1000,11,0.198,16.2,0.024944,0.049321,0.042292,0.017535,0.011677,...,0.028333,0.036805,0.051626,0.031819,0.013516,0.019276,0.030766,0.016513,0.035420,0.060132
75352,chr2,1500,19,0.363,16.6,0.023001,0.060919,0.037635,0.032618,0.009176,...,0.017349,0.060272,0.051320,0.069909,0.030497,0.024371,0.053064,0.016913,0.066830,0.065956
75353,chr2,2000,9,0.177,17.0,0.021824,0.065733,0.035504,0.039946,0.008337,...,0.011018,0.073765,0.053680,0.079113,0.051404,0.034984,0.067165,0.025820,0.096774,0.073378
75354,chr2,2500,1,0.028,15.2,0.009635,0.006711,0.004762,0.006711,0.012637,...,0.047943,0.035354,0.040974,0.031301,0.009788,0.004927,0.009879,0.002084,0.014773,0.012006

In [7]:
n_windows=data_1.shape[0]
print("Number of windows:", n_windows)

Number of windows: 479213

In [8]:
avg_snps=data_1['SNPs'].mean()
print('Average number of SNPs per window:',avg_snps)

Average number of SNPs per window: 67.85030873536402

## when window 10kb, step 5kb

In [11]:
data_10 =pd.read_csv(input_10, sep="\t")
data_10

,CHR,POS,SNPs,Fraction_window,Aver_min_coverage,s1_VS_s2,s1_VS_s3,s1_VS_s4,s1_VS_s5,s1_VS_s6,...,s11_VS_s12,s11_VS_s13,s11_VS_s14,s11_VS_s15,s12_VS_s13,s12_VS_s14,s12_VS_s15,s13_VS_s14,s13_VS_s15,s14_VS_s15
0,chr1,5000,337,0.233,19.7,0.014736,0.042511,0.031443,0.022316,0.012921,...,0.035822,0.033173,0.043971,0.066082,0.030865,0.030913,0.069545,0.031943,0.079325,0.074802
1,chr1,10000,483,0.479,21.6,0.016529,0.042419,0.038058,0.020297,0.013314,...,0.034691,0.037957,0.041822,0.058727,0.036450,0.038086,0.068252,0.036418,0.075864,0.060795
2,chr1,15000,256,0.480,23.4,0.017501,0.043107,0.055995,0.022953,0.013441,...,0.030752,0.041201,0.043610,0.048346,0.040756,0.042503,0.063997,0.046416,0.072289,0.035444
3,chr1,20000,192,0.487,23.4,0.014081,0.042542,0.056289,0.025576,0.011830,...,0.034428,0.031882,0.045815,0.053497,0.029905,0.031005,0.054930,0.033869,0.057688,0.036384
4,chr1,25000,150,0.459,23.2,0.017383,0.047256,0.050520,0.019733,0.011442,...,0.033619,0.045770,0.057865,0.065114,0.028822,0.037518,0.055389,0.026844,0.045603,0.030684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55121,chrX,45990000,159,0.790,20.2,0.020261,0.030494,0.101565,0.085050,0.013555,...,0.046362,0.136892,0.055463,0.122363,0.184836,0.075869,0.078003,0.061419,0.302457,0.158429
55122,chrX,45995000,236,0.799,20.5,0.014683,0.024803,0.077741,0.057897,0.010643,...,0.046807,0.088224,0.043436,0.088022,0.136501,0.051226,0.064533,0.052710,0.211952,0.107532
55123,chrX,46000000,220,0.820,21.1,0.014967,0.028165,0.080894,0.048961,0.012132,...,0.041459,0.072433,0.036364,0.089926,0.112974,0.040105,0.069598,0.047955,0.204402,0.105648
55124,chrX,46005000,197,0.880,20.9,0.016810,0.030378,0.084015,0.066916,0.015766,...,0.039254,0.075801,0.041083,0.118303,0.117699,0.057761,0.087799,0.032515,0.222657,0.140526
55125,chrX,46010000,122,0.433,20.5,0.015614,0.025580,0.064032,0.068155,0.013207,...,0.045195,0.078373,0.048435,0.097269,0.132561,0.072739,0.069614,0.026545,0.188930,0.125698

In [13]:
n_windows=data_10.shape[0]
print("Number of windows:", n_windows)

Number of windows: 55126

In [14]:
avg_snps=data_10['SNPs'].mean()
print('Average number of SNPs per window:',avg_snps)

Average number of SNPs per window: 589.8226970939303

## when window 100kb, step 50kb

In [12]:
data_100 = pd.read_csv(input_100, sep="\t")
data_100

,CHR,POS,SNPs,Fraction_window,Aver_min_coverage,s1_VS_s2,s1_VS_s3,s1_VS_s4,s1_VS_s5,s1_VS_s6,...,s11_VS_s12,s11_VS_s13,s11_VS_s14,s11_VS_s15,s12_VS_s13,s12_VS_s14,s12_VS_s15,s13_VS_s14,s13_VS_s15,s14_VS_s15
0,chr1,50000,2008,0.395,23.3,0.015807,0.045128,0.056980,0.020025,0.012275,...,0.032298,0.040120,0.048022,0.057150,0.029852,0.037280,0.054833,0.035272,0.052911,0.042593
1,chr1,100000,2122,0.508,23.3,0.014663,0.047334,0.065332,0.018948,0.012250,...,0.034634,0.043912,0.060508,0.060472,0.025649,0.038743,0.045473,0.036787,0.042658,0.038028
2,chr1,150000,3244,0.592,23.0,0.014854,0.042902,0.061478,0.020093,0.015213,...,0.035463,0.040714,0.080795,0.073360,0.026040,0.046534,0.046678,0.051922,0.050617,0.030429
3,chr1,200000,4379,0.618,22.4,0.016186,0.042733,0.064318,0.021724,0.015997,...,0.034849,0.037100,0.079540,0.074001,0.028150,0.047561,0.048619,0.054306,0.054328,0.028023
4,chr1,250000,3929,0.597,22.1,0.015405,0.044179,0.069797,0.022432,0.014747,...,0.035441,0.036707,0.084641,0.075144,0.029077,0.050916,0.048352,0.058140,0.054684,0.030555
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5643,chrX,45800000,2108,0.597,18.6,0.015890,0.032141,0.076041,0.054212,0.013644,...,0.039904,0.106736,0.047295,0.081215,0.144103,0.059194,0.059581,0.053498,0.226097,0.110201
5644,chrX,45850000,1855,0.637,18.9,0.015923,0.031365,0.083513,0.061986,0.014327,...,0.049846,0.105911,0.049350,0.099151,0.141950,0.059729,0.064556,0.049119,0.235663,0.125615
5645,chrX,45900000,1993,0.611,18.9,0.016936,0.033037,0.073423,0.059638,0.014632,...,0.044658,0.091594,0.046788,0.092051,0.122745,0.058380,0.062033,0.041601,0.201111,0.113801
5646,chrX,45950000,2249,0.638,19.6,0.017137,0.029417,0.068993,0.058771,0.013671,...,0.038904,0.083675,0.044574,0.082628,0.114643,0.054865,0.061239,0.039932,0.187331,0.107216
5647,chrX,46000000,1167,0.458,20.3,0.017587,0.025852,0.082503,0.066265,0.013099,...,0.043054,0.090806,0.046102,0.100087,0.128013,0.055960,0.076342,0.043446,0.224748,0.130265

In [15]:
n_windows=data_100.shape[0]
print("Number of windows:", n_windows)

Number of windows: 5648

In [16]:
avg_snps=data_100['SNPs'].mean()
print('Average number of SNPs per window:',avg_snps)

Average number of SNPs per window: 5755.784348441926

## assesses FST variability for each sliding-window size

1. Calculates the IQR of FST values for each farm pair.
2. Calculates the median of these pair-specific IQRs across all farm pairs to summarize overall FST variability for each window size.

In [ ]:
## function to calculate IQR of FST for each pair in each windowsize
def fst_iqr(df):
    fst_cols = df.columns[5:]
    return df[fst_cols].quantile(0.75) - df[fst_cols].quantile(0.25)

iqr_1kb = fst_iqr(data_1)
iqr_10kb = fst_iqr(data_10)
iqr_100kb = fst_iqr(data_100)

In [18]:
iqr_1kb

s1_VS_s2      0.024935
s1_VS_s3      0.055440
s1_VS_s4      0.095339
s1_VS_s5      0.026963
s1_VS_s6      0.009730
                ...
s12_VS_s14    0.033510
s12_VS_s15    0.071240
s13_VS_s14    0.030365
s13_VS_s15    0.072458
s14_VS_s15    0.077489
Length: 105, dtype: float64

In [ ]:
# median of all pairs' IQRs in each windowsize

print("Median FST IQR of all pairs in each windowsize FST data")
print("1 kb:", iqr_1kb.median().round(3))
print("10 kb:", iqr_10kb.median().round(3))
print("100 kb:", iqr_100kb.median().round(3))

Median FST IQR of all pairs in each windowsize FST data
1 kb: 0.052
10 kb: 0.041
100 kb: 0.028